<?php if ( ! defined( 'ABSPATH' ) ) exit;
/* 
Image Resizer
Author: Sam Mittelstaedt <smittelstaedt@jbs.org>
Description: Resize images on demand and eliminate duplicate images generated by WordPress.
Based on Better Image Sizes: https://wordpress.org/plugins/better-image-sizes/ which is based on Fly Dynamic Image Resizer

===== FUNCTION LIST =====
sis_image_sizes_resizer::__construct() - Initialize the image resizer
sis_image_sizes_resizer::init_directories() - Initialize the image resizer directories
sis_image_sizes_resizer::blog_switched() - Switch the image resizer directories when switching blogs
sis_image_sizes_resizer::get_sis_dir() - Get the image resizer directory
sis_image_sizes_resizer::check_sis_dir() - Check the image resizer directory
sis_image_sizes_resizer::sis_dir_writable() - Check if the image resizer directory is writable
sis_image_sizes_resizer::delete_all_sis_images() - Delete all image resizer images

*/

define( 'SIS_BASE', 'sis_image_sizes' );
define( 'SIS_RESIZER_URL', URL_SAM_RESIZER );
define( 'SIS_RESIZER_DIR', DIR_SAM_RESIZER );


if( ! defined('SIS_ALLOWED_MIME_TYPES') ){
	define( 'SIS_ALLOWED_MIME_TYPES', array( 'image/jpeg', 'image/png', 'image/webp' ) );
}

if( ! class_exists('sis_image_sizes_resizer') ){
    class sis_image_sizes_resizer{
        private $detector = false;
        private $sis_dir = '';

        function __construct(){
            // Only initialize directories for the current site
            add_action('plugins_loaded', array($this, 'init_directories'));
            
            require_once SIS_RESIZER_DIR.'/focal-point.php';

            add_action('admin_menu', array($this, 'admin_menu_item'));
            add_filter('media_row_actions', array($this, 'media_row_action'), 10, 2);
            add_filter('attachment_fields_to_edit', array($this, 'attachment_fields_to_edit'), 10, 2);
            add_action('delete_attachment', array($this, 'delete_attachment_sis_images'));
            
            // Only hook into switch_blog when actually uploading/managing media
            if (
                (defined('DOING_AJAX') && DOING_AJAX && isset($_REQUEST['action']) && in_array($_REQUEST['action'], ['upload-attachment', 'query-attachments'])) ||
                (is_admin() && function_exists('get_current_screen') && get_current_screen() && in_array(get_current_screen()->base, ['upload', 'post']))
            ) {
                add_action('switch_blog', array($this, 'blog_switched'));
            }
            
            add_filter('intermediate_image_sizes_advanced', array($this, 'remove_disabled_image_sizes'), 10, 1);
            add_filter('sis_get_attachment_image_attributes', array($this, 'retina_attribute'), 10, 4);

            if(intval(get_option('sis_disable_big_image_size_threshold', 0)) === 1){
                add_filter('sis_image_size_threshold', '__return_false');
            }
        }

        function init_directories() {
            // Only initialize for current site
            $current_blog_id = get_current_blog_id();
            
            // Skip if we've already initialized for this site
            if (!empty($this->sis_dir) && strpos($this->sis_dir, '/sites/' . $current_blog_id . '/') !== false) {
                return;
            }
            
            $this->sis_dir = apply_filters('sis_dir_path', $this->get_sis_dir());
            $this->check_sis_dir();
        }

        function blog_switched(){
            // Only process if we're actually switching blogs and dealing with media
            $new_blog_id = get_current_blog_id();
            if (!empty($this->sis_dir) && strpos($this->sis_dir, '/sites/' . $new_blog_id . '/') !== false) {
                // Already on the correct blog, no need to switch
                return;
            }
            
            // Clear WordPress upload dir cache
            wp_get_upload_dir(true);
            // Reset the sis_dir
            $this->sis_dir = '';
            $this->init_directories();
        }

        function get_sis_dir($path = ''){
            if(empty($this->sis_dir)){
                $wp_upload_dir = wp_upload_dir();
                $base_dir = $wp_upload_dir['basedir'];
                
                // Debug logging
                //error_log("Attempting to access base_dir: " . $base_dir);
                //error_log("Current blog ID: " . get_current_blog_id());
                //error_log("Upload dir structure: " . print_r($wp_upload_dir, true));
                
                // Create img directory path
                $img_dir = $base_dir . DIRECTORY_SEPARATOR . 'img';
                //error_log("Attempting to create/access img_dir: " . $img_dir);
                
                // Check/create parent directories with proper permissions
                if(!is_dir($base_dir)){
                    //error_log("Base directory doesn't exist: " . $base_dir);
                    if(!wp_mkdir_p($base_dir)){
                        //error_log("Failed to create base upload directory: " . $base_dir);
                        return false;
                    }
                    chmod($base_dir, 0755);
                }

                // Return full path
                $final_path = $img_dir . ($path !== '' ? DIRECTORY_SEPARATOR . $path : '');
                //error_log("Final path being returned: " . $final_path);
                return $final_path;
            } else {
                return $this->sis_dir . ($path !== '' ? DIRECTORY_SEPARATOR . $path : '');
            }
        }

        function check_sis_dir(){
            if(!empty($this->sis_dir) && !is_dir($this->sis_dir)){
                // Check parent directory permissions first
                $parent_dir = dirname($this->sis_dir);
                if(!is_dir($parent_dir)){
                    if(!wp_mkdir_p($parent_dir)){
                        //error_log("Failed to create parent directory: " . $parent_dir);
                        return false;
                    }
                    chmod($parent_dir, 0755);
                }
                
                if(!is_writable($parent_dir)){
                    //error_log("Parent directory not writable: " . $parent_dir);
                    return false;
                }
                
                // Create directory with explicit permissions
                if(!wp_mkdir_p($this->sis_dir)){
                    //error_log("Failed to create JIS directory: " . $this->sis_dir);
                    return false;
                }
                chmod($this->sis_dir, 0755);
            }
            return true;
        }

        function sis_dir_writable(){
            return is_dir( $this->sis_dir ) && wp_is_writable( $this->sis_dir );
        }

        function delete_all_sis_images(){
            if( ! function_exists( 'WP_Filesystem' ) ) return false;
            WP_Filesystem();
            global $wp_filesystem;
            if( $wp_filesystem->rmdir( $this->get_sis_dir(), true ) ){

                $this->check_sis_dir();
                return true;
            }

            return false;
        }

        function delete_attachment_sis_images( $attachment_id = 0 ){
            if( ! function_exists( 'WP_Filesystem' ) ) return false;
            WP_Filesystem();
            global $wp_filesystem;
            return $wp_filesystem->rmdir( $this->get_sis_dir( $attachment_id ), true );
        }

        /* Delete all images generated by WordPress */
        function sis_delete_wp_generated_images(){
            echo '<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;"><h2>Deleting Images Generated by WordPress</h2>';
            $i=0;
            $d=0;
            $clones = array();
            global $wpdb;

            $attachments = get_posts(array(
                'post_type' => 'attachment',
                'posts_per_page' => -1,
                'post_status' => 'any',
                'suppress_filters' => true,
                'fields' => 'ids',
                'nopaging' => true,
                'numberposts' => -1
            ));

            $total = count($attachments);
            echo '<h3>Processing ' . $total . ' attachments...</h3>';

            // Get upload directory info
            $upload_dir = wp_upload_dir();
            if(!$upload_dir['basedir']){
                echo '<p style="margin:.1em 2em; color:#ff0000;">No upload directory found</p>';
                return false;
            }

            foreach($attachments as $ID){
                $i++;
                // Get attachment metadata
                $metadata = wp_get_attachment_metadata($ID);
                if(!$metadata){
                    echo '<p style="margin:.1em 2em; color:#ff0000;">No metadata for attachment ID: ' . $ID . '</p>';
                    continue;
                }else{
                    $meta_before = $metadata;
                }

                // Get path to original image
                $raw_name = $metadata['file'];
                //Get file name without extension or directory prefix
                $file_name = basename($raw_name);
                $file_name_no_ext = pathinfo($file_name, PATHINFO_FILENAME);

                $original_file = $upload_dir['basedir'] . '/' . $raw_name;
                $path_parts = pathinfo($original_file);

                echo '<div style="border-bottom: 1px solid #666; padding-bottom: 10px;"><ul>'.$i.' [' . $ID . '] ' . $raw_name . ' | <b>' . $file_name_no_ext . '</b> | ' . $original_file;


                // Delete all registered image sizes
                if(isset($metadata['sizes']) && is_array($metadata['sizes'])){
                    foreach($metadata['sizes'] as $size => $size_info){
                        $size_file = $path_parts['dirname'] . '/' . $size_info['file'];
                        if(file_exists($size_file)){
                            echo '<li style="padding-left: 20px;">' . $size_file . '</li>';
                            @unlink($size_file);
                            //unset this size from metadata
                            unset($metadata['sizes'][$size]);
                            $d++;
                        }
                    }
                }
                echo '</ul></div>';

                // Update attachment metadata without sizes
                $metadata['sizes'] = array();
                wp_update_attachment_metadata($attachment_id, $metadata);

            }
            echo '<h3>Deleted <strong>' . $d . '</strong> duplicates for <strong>' . $i . '</strong> images</h3>';
            echo '<textarea style="width:100%; height:200px;">' . implode("\n", $clones) . '</textarea>';
            echo '</div>';
        }


        /* Detect duplicate images generated by WordPress */
        function sis_find_wp_generated_clones(){
            echo '<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;"><h2>Identifying Cloned Images Generated by WordPress Plugins</h2>';
            $i=0;
            $d=0;
            $clones = array();
            global $wpdb;
			$upload_dir = wp_upload_dir();

            $attachments = get_posts(array(
                'post_type' => 'attachment',
                'posts_per_page' => -1,
                'post_status' => 'any',
                'meta_key' => '_wp_attachment_metadata',
            ));
            foreach($attachments as $attachment){
                $i++;

                // Get attachment metadata
                $metadata = wp_get_attachment_metadata($attachment->ID);
                if(!$metadata) return false;

                // Get path to original image
                $raw_name = $metadata['file'];
                //Get file name without extension or directory prefix
                $file_name = basename($raw_name);
                $file_name_no_ext = pathinfo($file_name, PATHINFO_FILENAME);

                $original_file = $upload_dir['basedir'] . '/' . $raw_name;
                $path_parts = pathinfo($original_file);

                echo '<ul style="border-bottom: 1px solid #666; padding-bottom: 10px;">[' . $attachment->ID . '] ' . $raw_name . ' | <b>' . $file_name_no_ext . '</b> | ' . $original_file;

                //Detect registered duplicates: Is this image file name a sub string of another image file name? Query where guid like %$file_name_no_ext%
                $query = "SELECT * FROM {$wpdb->prefix}posts WHERE post_type = 'attachment' AND post_status = 'inherit' AND post_mime_type IN ('image/jpeg', 'image/png', 'image/webp') AND LOWER(guid) LIKE '%" . strtolower($file_name_no_ext) . "%' AND guid NOT LIKE '%" . strtolower($file_name) . "%'";
                $results = $wpdb->get_results($query);
                foreach($results as $result){
                    $d++;
                    //Determine if this file is attached to a post
                    // Check if image is used as featured image
                    $featured_image_post = $wpdb->get_var($wpdb->prepare(
                        "SELECT post_id FROM {$wpdb->prefix}postmeta WHERE meta_key = '_thumbnail_id' AND meta_value = %d",
                        $result->ID
                    ));

                    // Check if image is used in post content
                    $content_usage = $wpdb->get_var($wpdb->prepare(
                        "SELECT ID FROM {$wpdb->prefix}posts WHERE post_content LIKE %s",
                        '%' . $wpdb->esc_like($result->guid) . '%'
                    ));

                    if ($featured_image_post) {
                        $post = get_post($featured_image_post);
                        $is_used = '<span style="color:#008000;">Featured image for: ' . $post->post_title . '</span>';
                    } else if ($content_usage) {
                        $post = get_post($content_usage); 
                        $is_used = '<span style="color:#0000ff;">Used in content: ' . $post->post_title . '</span>';
                    } else {
                        $is_used = '<span style="color:#ff0000;">Not in use</span>';
                    }

                    $clones[] = $result->ID . '|' . $result->guid;
                    echo '<li style="padding-left: 20px; font-weight:bold;">[' . $result->ID . '] CLONE: ' . str_replace($file_name_no_ext,$file_name_no_ext.'<span style="color:#ff0000;">',$result->guid) . '</span> ' . $is_used . '</li>';
                }

                echo '</ul>';
            }
            echo '<h3>Identified <strong>' . $d . '</strong> clones for <strong>' . $i . '</strong> images</h3>';
            echo '<textarea style="width:100%; height:200px;">' . implode("\n", $clones) . '</textarea>';
            echo '</div>';
        }


        //Identify and delete unregistered images and sizes: Build array of all registered images and sizes then scan main directory for all images then check to see if they are in the array
        function sis_find_orphaned_images($delete = false){
            echo '<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;"><h2>Identifying Orphaned Images</h2>';
            $i=0;
            $d=0;
            $orphaned = array();
            //Build one array of all registered images and sizes
            $regImg = array();

            $unregImg = array();
            $checkImg = array(); // Initialize array

            $attachments = get_posts(array(
                'post_type' => 'attachment',
                'posts_per_page' => -1,
                'post_status' => 'any',
                'suppress_filters' => true,
                'fields' => 'ids',
                'nopaging' => true,
                'numberposts' => -1
            ));

            $total = count($attachments);
            echo '<h3>Processing ' . $total . ' attachments...</h3>';

            if (!$attachments) {
                echo '<div class="error"><p>No attachments found</p></div>';
                return false;
            }

            // Get upload directory info
            $upload_dir = wp_upload_dir();
            if(!$upload_dir['basedir']){
                echo '<p style="margin:.1em 2em; color:#ff0000;">No upload directory found</p>';
                return false;
            }

            foreach($attachments as $ID){
                $i++;

                // Get attachment metadata
                $metadata = wp_get_attachment_metadata($ID);
                if(!$metadata) {
                    //Get the file path from the post guid
                    $file_path = get_post_meta($ID, '_wp_attached_file', true);
                    if(!$file_path){
                        //Get the file path from the post guid and replace site url with abspath
                        $file_path = str_replace(home_url(), ABSPATH, get_post_field('guid', $ID));
                    }
                    //Check if the file path is a valid image
                    if(!$file_path){
                        echo '<div><p style="color:#ff0000;">No Metadata or File Path found for attachment ID: ' . $ID . '</p></div>';
                    }else{
                        $regImg[$ID] = $file_path;
                    }
                    continue;
                }


                if (!isset($metadata['file'])) {
                    //Try to fill in the file pate
                    $metadata['file'] = get_post_meta($ID, '_wp_attached_file', true);
                    if(!$metadata['file']) {
                        //Get the file path from the post guid if nothing else works
                        $file_path = get_post_field('guid', $ID);

                        if(!$file_path) {
                            echo '<div class="error"><p>No file path found in metadata for attachment ID: ' . $ID . '</p></div>';
                            continue;
                        }

                        //Remove the upload URL from the file path
                        $metadata['file'] = str_replace(wp_upload_dir()['baseurl'], '', $file_path);
                        //Remove the site URL from the file path/assets to deal with previous configuration
                        $metadata['file'] = str_replace(home_url('/assets'), '', $metadata['file']);
                    }
                }

                $regImg[] = $metadata['file'];
                if(isset($metadata['sizes']) && is_array($metadata['sizes'])){
                    foreach($metadata['sizes'] as $size => $size_info){
                        if (!isset($size_info['file'])) {

                            echo '<div class="error"><p>Invalid size info for attachment ID: ' . $ID . ', size: ' . $size . '</p></div>';
                            continue;
                        }
                        $regImg[] = $size_info['file'];
                    }
                }
            }

            echo '<h3>Registered Images</h3>';
            echo '<textarea style="width:100%; height:500px;">';
            foreach($regImg as $ID => $file_path){
                echo $ID . '|' . $file_path . "\n";
            }
            echo '</textarea>';



            //Scan user image directories
            $main_dir = wp_upload_dir()['basedir'];

            if (!$main_dir || !is_dir($main_dir)) {
                echo '<div class="error"><p>Invalid main directory path</p></div>';
                return false;
            }

            //Directories to scan
            $dirs = array(
                '/',
                '/2024/',
                '/2025/',
                '/about/',
                '/agenda30/',
                '/concon/',
                '/constitution/', 
                '/covid19/',
                '/education/',
                '/globalism/',
                '/immigration/',
                '/lecf/',
                '/logo/',
                '/nafta/',
                '/nau/',
                '/sylp/',
                '/states/',
                '/tna/',
                '/trade/',
                '/un/',
                '/usmca/',
            );

            foreach($dirs as $dir){
                $checkDir = $main_dir . $dir;
                if(is_dir($checkDir)){
                    echo '<h3>CHECKING: ' . $checkDir . '...</h3>';
                }else{
                    //echo '<h3>NOT FOUND: ' . esc_html($checkDir) . '</h3>';
                    continue;
                }

                $files = scandir($checkDir);
                if ($files === false) {
                    echo '<div class="error"><p>Unable to scan directory: ' . esc_html($checkDir) . '</p></div>';
                    continue;
                }

                foreach($files as $file){
                    if(is_file($checkDir . '/' . $file)){
                        $checkImg[] = $file;
                        if(!in_array($file, $regImg)){
                            if($delete){
                                unlink($checkDir . $file);
                                $status = 'DELETED: ';
                                $color = '#cc0000';
                            }else{
                                $status = 'ORPHAN: ';
                                $color = '#0000ff';
                            }
                            $unregImg[] = $status . $checkDir . $file;
                        }else{
                            $status = 'FOUND: ';
                            $color = '#008000';
                            //Remove the file from the regImg array
                            unset($regImg[$file]);
                        }
                        echo '<p style="margin:.1em 2em; color:' . $color . ';">' . $status . $checkDir . $file . '</p>';
                    }

                }
            }

            if (empty($unregImg)) {
                echo '<h3>No orphaned images found</h3>';
            }else{
                echo '<h3>Identified <strong>' . count($unregImg) . '</strong> orphaned images</h3>';
                echo '<textarea style="width:100%; height:720px;">' . esc_textarea(implode("\n", $unregImg)) . '</textarea>';
            }

            echo '<h3>Registered Images that are missing from the user directory</h3>';
            echo '<textarea style="width:100%; height:720px;">' . esc_textarea(implode("\n", $regImg)) . '</textarea>';
            echo '</div>';

        }


        /* FIX JBS IMAGE DIRECTORY
        * Consolidate sub-folders into main upload directory
        * Scan specific list of sub-folders and move files into main upload directory
        * Delete the sub-folders
        * Update the attachment metadata and guid to reflect the new file path
        */
        function sis_consolidate_subfolders(){
            global $wpdb;
            $execute = false; // Set to true to execute the changes

            echo '<div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;"><h2>Consolidating Sub-folders into Main Upload Directory</h2>';

            //Get the main upload directory
            $upload_dir = wp_upload_dir();
            $main_dir = $upload_dir['basedir'];

            //Directories to scan
            $dirs = array(
                '/about/',
                '/agenda30/',
                '/concon/',
                '/constitution/', 
                '/covid19/',
                '/education/',
                '/globalism/',
                '/immigration/',
                '/lecf/',
                '/logo/',
                '/nafta/',
                '/nau/',
                '/states/',
                '/sylp/',
                '/tna/',
                '/trade/',
                '/un/',
                '/usmca/',
            );

            foreach($dirs as $dir){
                $checkDir = $main_dir . $dir;
                if(is_dir($checkDir)){
                    echo '<h3>CHECKING: ' . $checkDir . '</h3>';
                }else{
                    //echo '<h3>NOT FOUND: ' . esc_html($checkDir) . '</h3>';
                    continue;
                }

                $files = scandir($checkDir);
                if ($files === false) {
                    echo '<div class="error"><p>Unable to scan directory: ' . esc_html($checkDir) . '</p></div>';
                    continue;
                }

                foreach($files as $file){
                    if(is_file($checkDir . '/' . $file)){
                        echo '<div style="margin:1em 0em .1em 2em;">' . $checkDir . $file . '</div>';
                        $used = false;

                        // Get attachment ID from original file path
                        // Convert file path to URL for attachment_url_to_postid()
                        $upload_url = wp_upload_dir()['baseurl'];
                        //This is a dev site. The attachment URLs are saved with the production url.
                        $production_url = WP_CONTENT_URL;
                        $attachment_url = str_replace($main_dir, $production_url, $checkDir . $file);
                        //$attachment_id = attachment_url_to_postid($attachment_url);
                        //Get attachment ID from guid
                        $post = $wpdb->get_results($wpdb->prepare("SELECT ID FROM $wpdb->posts WHERE guid = %s", $attachment_url));
                        $attachment_id = $post[0]->ID;

                        if($attachment_id){
                            echo '<div style="color:#008000; margin:.1em 2em;">Attachment ID found ' . $attachment_id . ' for ' . $attachment_url . '</div>';

                            //Check if the file to be moved is attached to or contained in a post or postmeta before moving it
                            // Check if file is used as featured image
                            $featured_image_query = $wpdb->get_results($wpdb->prepare(
                                "SELECT post_id FROM $wpdb->postmeta WHERE meta_key = '_thumbnail_id' AND post_type != 'attachment' AND meta_value = %d",
                                $attachment_id
                            ));
                            if(!empty($featured_image_query)){
                                $post_ids = array();
                                foreach($featured_image_query as $result){
                                    $post_ids[] = $result->post_id;
                                }
                                echo '<div style="color:#0000ff; margin:.1em 2em;">File ' . $file . ' is used as featured image for '.implode(', ', $post_ids).'</div>';
                                $used = true;
                            }

                            // Check if file is in post content
                            $content_query = $wpdb->get_results($wpdb->prepare(
                                "SELECT ID FROM $wpdb->posts WHERE post_content LIKE %s",
                                '%' . $file . '%'
                            ));
                            if(!empty($content_query)){
                                $post_ids = array();
                                foreach($content_query as $result){
                                    $post_ids[] = $result->ID;
                                }
                                echo '<div style="color:#0000ff; margin:.1em 2em;">File ' . $file . ' is used in post content for '.implode(', ', $post_ids).'</div>';
                                $used = true;
                            }

                            // Check if file is in postmeta
                            $meta_query = $wpdb->get_results($wpdb->prepare(
                                "SELECT post_id FROM $wpdb->postmeta WHERE meta_value LIKE %s",
                                '%' . $file . '%'
                            ));
                            if(!empty($meta_query)){
                                $post_ids = array();
                                foreach($meta_query as $result){
                                    $post_ids[] = $result->post_id;
                                }
                                echo '<div style="color:#0000ff; margin:.1em 2em;">File ' . $file . ' is in postmeta for '.implode(', ', $post_ids).'</div>';
                                $used = true;
                            }

                        }else{
                            echo '<div style="color:#cc0000; margin:.1em 2em;">Attachment ID not found for ' . $attachment_url . '</div>';
                        }

                        /* Handling Logic
                        if used, skip
                        else check if file exists in main upload directory
                            if exists, delete from sub-folder
                            else move file to main upload directory
                        */
                        if($used){
                            echo '<div style="color:#0000ff; margin:.1em 2em;">SKIP File ' . $file . ' is used in a post or postmeta</div>';
                        }else{
                            echo '<div style="color:#cc0000; margin:.1em 2em;">File ' . $file . ' is not used in any post</div>';

                            //Move the file to the main upload directory
                            $new_file = $main_dir . '/' . $file;
                            if(file_exists($new_file)){
                                echo '<div style="color:#008000; margin:.1em 2em;">File ' . $file . ' already exists in the main upload directory</div>';

                                //Delete the file from the sub-folder
                                if($execute){
                                    unlink($checkDir . '/' . $file);
                                }
                                echo '<div style="color:#cc0000; margin:.1em 2em;">DELETED ' . $checkDir . $file . '</div>';

                                // Delete attachment and all associated metadata from the database
                                if($attachment_id){
                                    if($execute){
                                        wp_delete_attachment($attachment_id, true);
                                    }
                                    echo '<div style="color:#cc0000; margin:.1em 2em;">Attachment ' . $attachment_id . ' deleted from the database</div>';
                                }

                            }else{
                                if($attachment_id){
                                    if($execute){
                                        rename($checkDir . '/' . $file, $new_file);
                                    }
                                    echo '<div style="color:#008000; margin:.1em 2em;">File ' . $file . ' moved to the main upload directory</div>';

                                    //Update the attachment metadata and guid to reflect the new file path
                                    $metadata = wp_get_attachment_metadata($attachment_id);
                                    
                                    // Update the file path to reflect the new file path
                                    $metadata['file'] = basename($new_file);
                                    if($execute){
                                        wp_update_attachment_metadata($attachment_id, $metadata);
                                        // Update the guid to reflect the new file path
                                        $guid = $upload_dir['baseurl'] . '/' . $file;
                                        $wpdb->update(
                                            $wpdb->posts,
                                            array('guid' => $guid),
                                            array('ID' => $attachment_id)
                                        );
                                        // Update the post meta to reflect the new file path
                                        update_post_meta($attachment_id, '_wp_attached_file', basename($new_file));
                                        update_post_meta($attachment_id, '_wp_attachment_metadata', $metadata);
                                    }
                                    echo '<div style="color:#008000; margin:.1em 2em;">File ' . $file . ' info updated.</div>';
                                }else{
                                    //Delete the file from the sub-folder
                                    if($execute){
                                        unlink($checkDir . '/' . $file);
                                    }
                                    echo '<div style="color:#cc0000; margin:.1em 2em;">DELETED ' . $checkDir . $file . '</div>';
                                }
                            }
                        }
                    }
                }
            }
            echo '</div>';
        }




        
        //Admin Menu Item
        function admin_menu_item(){
            add_management_page(
                __( 'Image Resizer', 'sis_image_sizes' ),
                __( 'Image Resizer', 'sis_image_sizes' ),
                'manage_options',
                SIS_BASE,
                array( $this, 'options_page' )
            );


            add_filter( 'plugin_action_links_' . SIS_BASE, function( $links, $file ){
                array_unshift( $links, '<a href="tools.php?page=' . SIS_BASE . '">' . __( 'Settings', '_new-plugin' ) . '</a>' );
                return $links;
            }, 10, 2 );
        }

        //Get all image sizes
        function get_all_image_sizes(){
            global $_wp_additional_image_sizes;
            $sizes = array();
            foreach( get_intermediate_image_sizes() as $_size ){
                if( in_array( $_size, array( 'thumbnail', 'medium', 'medium_large', 'large' ) ) ){
                    $sizes[ $_size ]['w'] = get_option( "{$_size}_size_w" );
                    $sizes[ $_size ]['h'] = get_option( "{$_size}_size_h" );
                }elseif( isset( $_wp_additional_image_sizes[ $_size ] ) ){
                    $sizes[ $_size ] = array(
                        'w' => $_wp_additional_image_sizes[ $_size ]['width'],
                        'h' => $_wp_additional_image_sizes[ $_size ]['height'],
                    );
                }
            }
            return $sizes;
        }

        //Options Page
        function options_page(){
            if( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'delete_all_sis_images' ) ){
                $this->delete_all_sis_images();
                echo '<div class="updated"><p>' . esc_html__( 'All cached images have been deleted.', 'jbs-image-sizes' ) . '</p></div>';
            }elseif( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'delete_wp_generated_images' ) ){
                echo '<h3>Start Deleting Auto Generated Images...</h3>';
                $this->sis_delete_wp_generated_images();
                exit;
            }elseif( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'find_wp_generated_clones' ) ){
                echo '<h3>Start Identifying Cloned Images...</h3>';
                $this->sis_find_wp_generated_clones();
                exit;
            }elseif( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'find_orphaned_images' ) ){
                echo '<h3>Start Identifying Orphaned Images...</h3>';
                $this->sis_find_orphaned_images();
                exit;
            }elseif( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'delete_orphaned_images' ) ){
                echo '<h3>Start Deleting Orphaned Images...</h3>';
                $this->sis_find_orphaned_images(true);
                exit;
            }elseif( isset( $_POST['sis_nonce'] ) && wp_verify_nonce( $_POST['sis_nonce'], 'consolidate_subfolders' ) ){
                echo '<h3>Start Consolidating Sub-folders...</h3>';
                $this->sis_consolidate_subfolders();
                exit;


            }elseif( isset( $_POST['sis_disabled_sizes_nonce'] ) && wp_verify_nonce( $_POST['sis_disabled_sizes_nonce'], 'disabled_sizes' ) ){
                $sizes = $this->get_all_image_sizes();
                $sis_disabled_sizes = array();
                foreach( $_POST['sis_disabled_sizes'] as $key => $value ){
                    if( isset( $sizes[ $key ] ) ){
                        $sis_disabled_sizes[ $key ] = intval( $value );
                    }
                }
                update_option( 'sis_disabled_sizes', $sis_disabled_sizes );
                echo '<div class="updated"><p>' . esc_html__( 'Disable autogenerated sizes updated.', 'jbs-image-sizes' ) . '</p></div>';
            }elseif( isset( $_POST['sis_disable_threshold_nonce'] ) && wp_verify_nonce( $_POST['sis_disable_threshold_nonce'], 'disable_threshold' ) ){
                $disable_threshold = 0;
                if( isset( $_POST['sis_disable_big_image_size_threshold'] ) ){
                    $disable_threshold = intval( $_POST['sis_disable_big_image_size_threshold'] );
                }
                update_option( 'sis_disable_big_image_size_threshold', $disable_threshold ? 1 : 0 );
                echo '<div class="updated"><p>' . esc_html__( 'Big image threshold updated.', 'jbs-image-sizes' ) . '</p></div>';
            }elseif( isset( $_GET['delete-jbs-image'], $_GET['ids'], $_GET['sis_nonce'] ) && wp_verify_nonce( $_GET['sis_nonce'], 'delete_sis_image' ) ){
                $ids = array_map( 'intval', array_map( 'trim', explode( ',', sanitize_key( $_GET['ids'] ) ) ) );
                if( ! empty( $ids ) ){
                    foreach( $ids as $id ){
                        $this->delete_attachment_sis_images( $id );
                    }
                    echo '<div class="updated"><p>' . esc_html__( 'All cached images for this media file have been deleted.', 'jbs-image-sizes' ) . '</p></div>';
                }
            } ?>

            <div class="wrap">
                <h2>JBS Image Resizer</h2>

                <div class="card">
                    <h3><?php esc_html_e( 'Images directory', 'jbs-image-sizes' ); ?></h3>
                    <p><code><?php echo esc_html( $this->get_sis_dir() ) ?></code></p>
                    <?php if( $this->sis_dir_writable() ): ?>
                        <p style="color:#7AD03A"><?php esc_html_e( 'Writeable', 'jbs-image-sizes' ) ?></p>
                    <?php else: ?>
                        <p style="color:#A00"><?php esc_html_e( 'Not Writeable - please make sure this folder exists and is writeable!', 'jbs-image-sizes' ) ?></p>
                    <?php endif ?>
                </div>

                <div class="card">
                    <h3><?php esc_html_e( 'Disable autogenerated sizes', 'jbs-image-sizes' ) ?></h3>
                    <p class="notice notice-info notice-large">
                        <?php esc_html_e( 'You should not disable thumbnail size', 'jbs-image-sizes' ); ?>
                    </p>
                    <form method="post" action=""><?php
                        wp_nonce_field( 'disabled_sizes', 'sis_disabled_sizes_nonce' );
                        $sis_disabled_sizes = get_option( 'sis_disabled_sizes', array() );
                        $sizes = $this->get_all_image_sizes();
                        foreach( $sizes as $size => $data ){
                            if( ! isset( $sis_disabled_sizes[ $size ] ) ){
                                $sis_disabled_sizes[ $size ] = 0;
                            } ?>
                            <label>
                                <input type="checkbox" name="sis_disabled_sizes[<?php echo esc_attr( $size ) ?>]" value="1" <?php checked( $sis_disabled_sizes[ $size ], 1 ) ?>>
                                <?php echo esc_html( $size ) ?> <small>(<?php echo esc_html( $data['w'] . 'x' . $data['h'] ) ?>)</small>
                            </label><br><?php
                        } ?>
                        <br><input class="button button-primary" value="<?php esc_html_e( 'Save', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>

                <div class="card">
                    <h3><?php esc_html_e( 'Disable big image size threshold', 'jbs-image-sizes' ) ?></h3>
                    <p><?php esc_html_e( 'WordPress will automatically scale down your uploaded images, if the original image width or height is above 2560px', 'jbs-image-sizes' ) ?></p>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'disable_threshold', 'sis_disable_threshold_nonce' ) ?>
                        <label>
                            <input type="checkbox" name="sis_disable_big_image_size_threshold" value="1" <?php checked( get_option( 'sis_disable_big_image_size_threshold', 0 ), 1 ) ?>>
                            <?php esc_html_e( 'disable auto-scaling of big images', 'jbs-image-sizes' ) ?>
                        </label><br><br>
                        <input class="button button-primary" value="<?php esc_html_e( 'Save', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>

                <div class="card">
                    <h3><?php esc_html_e( 'Delete cached images', 'jbs-image-sizes' ) ?></h3>
                    <p><?php esc_html_e( 'Delete all generated image sizes for all images', 'jbs-image-sizes' ) ?></p>
                    <p><small><?php esc_html_e( '* they will be regenerated instantly when you visit your website', 'jbs-image-sizes' ) ?></small></p>
                    <br>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'delete_all_sis_images', 'sis_nonce' ) ?>
                        <input class="button button-primary" value="<?php esc_html_e( 'Delete all', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>

                <div class="card">
                    <h3><?php esc_html_e( 'Delete Multiple Images Generated by WordPress', 'jbs-image-sizes' ) ?></h3>
                    <p><?php esc_html_e( 'Delete all generated images sizes for all images', 'jbs-image-sizes' ) ?></p>
                    <p><small><?php esc_html_e( '* Use thumbnail generator to regenerate enabled image sizes.', 'jbs-image-sizes' ) ?></small></p>
                    <br>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'delete_wp_generated_images', 'sis_nonce' ) ?>
                        <input class="button button-primary" value="<?php esc_html_e( 'Delete WP Generated Images', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>

                <div class="card">
                    <h3><?php esc_html_e( 'Identify Cloned Images', 'jbs-image-sizes' ) ?></h3>
                    <br>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'find_wp_generated_clones', 'sis_nonce' ) ?>
                        <input class="button button-primary" value="<?php esc_html_e( 'Find Cloned Images', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>                

                <div class="card">
                    <h3><?php esc_html_e( 'Identify Orphaned Images', 'jbs-image-sizes' ) ?></h3>
                    <br>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'find_orphaned_images', 'sis_nonce' ) ?>
                        <input class="button button-primary" value="<?php esc_html_e( 'Find Orphaned Images', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>

                    <form method="post" action="">
                        <?php wp_nonce_field( 'delete_orphaned_images', 'sis_nonce' ) ?>
                        <input class="button button-secondary" style="margin-top:10px;" value="<?php esc_html_e( 'Delete Orphaned Images', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div> 

                <div class="card">
                    <h3><?php esc_html_e( 'Consolidate Sub-folders into Main Upload Directory', 'jbs-image-sizes' ) ?></h3>
                    <br>
                    <form method="post" action="">
                        <?php wp_nonce_field( 'consolidate_subfolders', 'sis_nonce' ) ?>
                        <input class="button button-primary" value="<?php esc_html_e( 'Consolidate Sub-folders', 'jbs-image-sizes' ) ?>" type="submit">
                    </form>
                </div>                   

            </div><?php
        }

        function remove_disabled_image_sizes( $sizes ){
            $sis_disabled_sizes = get_option( 'sis_disabled_sizes', array() );
            
            // Loop through disabled sizes and remove them from the sizes array
            foreach( $sis_disabled_sizes as $size => $disabled ){
                if( $disabled && isset($sizes[$size]) ){
                    unset( $sizes[$size] );
                }
            }
            
            return $sizes;
        }

        function media_row_action( $actions, $post ){
            if( in_array( $post->post_mime_type, SIS_ALLOWED_MIME_TYPES ) ){
                $url = wp_nonce_url( admin_url( 'tools.php?page=' . SIS_BASE . '&delete-jbs-image&ids=' . $post->ID ), 'delete_sis_image', 'sis_nonce' );
                $actions['jbs-image-delete'] = '<a href="' . esc_url( $url ) . '" title="' . esc_attr( __( 'Delete all cached image sizes for this image', 'jbs-image-sizes' ) ) . '">' . __( 'Regenerate BIS images', 'jbs-image-sizes' ) . '</a>';
            }
            return $actions;
        }

        function attachment_fields_to_edit( $form_fields, $post ){
            if( in_array( get_post_mime_type( $post->ID ), SIS_ALLOWED_MIME_TYPES ) ){
                $url = wp_nonce_url( admin_url( 'tools.php?page=' . SIS_BASE . '&delete-jbs-image&ids=' . $post->ID ), 'delete_sis_image', 'sis_nonce' );
                $form_fields['regenerate_sis_images'] = array(
                    'value' => 1,
                    'label' => __( 'JBS Image Resizer', 'sis_image_sizes' ),
                    'input' => 'html',
                    'html' => '<a class="button button-small" href="' . esc_url( $url ) . '" title="' . esc_attr( __( 'Delete all cached image sizes for this image', 'jbs-image-sizes' ) ) . '">' . __( 'Regenerate', 'jbs-image-sizes' ) . '</a>'
                );
            }
            return $form_fields;
        }




        function get_sis_file_name( $file_name, $width, $height, $crop ){
            $file_name_only = pathinfo( $file_name, PATHINFO_FILENAME );
            $file_extension = strtolower( pathinfo( $file_name, PATHINFO_EXTENSION ) );
            $crop_extension = '';

            if( $crop === true || $crop === 1 ){
                $crop_extension = '-c';
            } elseif( $crop === 'face' ){
                $crop_extension = '-fd';
            } elseif( is_array( $crop ) ){
                if( isset($crop[0]) && is_numeric( $crop[0] ) ){
                    $crop_extension = '-f' . round( floatval( $crop[0] ) * 100 ) . '_' . round( floatval( $crop[1] ) * 100 );
                } else {
                    $crop_extension = '-' . implode( '', array_map( function( $position ){
                        if (is_array($position) && isset($position[0])) {
                            return $position[0];
                        }
                        return ''; // Return an empty string if $position is not valid
                    }, $crop ) );
                }
            }

            $filename =  $file_name_only . '-' . intval( $width ) . 'x' . intval( $height ) . $crop_extension . '.' . $file_extension;
            return $filename;
        }

        function get_sis_path( $absolute_path = '' ){
            $wp_upload_dir = wp_upload_dir();
            $path = $wp_upload_dir['baseurl'] . str_replace( $wp_upload_dir['basedir'], '', $absolute_path );
            return str_replace( DIRECTORY_SEPARATOR, '/', $path );
        }

        function get_attachment_image_src( $attachment_id = 0, $size = '', $crop = null ){
            if( $attachment_id < 1 || empty( $size ) ){
                return array();
            }

            if( $size == 'full' || ! in_array( get_post_mime_type( $attachment_id ), SIS_ALLOWED_MIME_TYPES ) ){
                $default_attachment = wp_get_attachment_image_src( $attachment_id, 'full' );
                if( is_array( $default_attachment ) ){
                    return array_combine( array( 'src', 'width', 'height', 'resized' ), $default_attachment );
                }
                return array();
            }

            $image = wp_get_attachment_metadata( $attachment_id );
            if( $image ){
                switch( gettype( $size ) ){
                    case 'array':
                        $width = $size[0];
                        $height = $size[1];
                        break;
                    default:
                        return array();
                }

                // fix for images with 0 width or height - do not crop them
                if( intval( $width ) === 0 || intval( $height ) === 0 ){
                    $crop = false;
                }

                // maybe load default focal point
                if( $crop === true || $crop === 1 ){
                    $crop = sanitize_focal_point( get_post_meta( $attachment_id, 'focal_point', true ) );
                }

                $sis_dir = $this->get_sis_dir( $attachment_id );
                $sis_file_path = $sis_dir . DIRECTORY_SEPARATOR . $this->get_sis_file_name( basename( isset($image['file']) ? $image['file'] : '' ), $width, $height, $crop );
                if( file_exists( $sis_file_path ) ){
                    $image_size = getimagesize( $sis_file_path );
                    if( ! empty( $image_size ) ){
                        return array(
                            'src' => $this->get_sis_path( $sis_file_path ),
                            'width' => $image_size[0],
                            'height' => $image_size[1],
                        );
                    }else{
                        return array();
                    }
                }

                $this->check_sis_dir();

				/* 250801 Handle cross-site image editor
				$image_editor is looking for /home2/jbs/public_html/assets/sites/7/sites/3/2025/By-Compact-Not-Command.jpg
				but it should be looking for /home2/jbs/public_html/assets/sites/3/2025/By-Compact-Not-Command.jpg
				*/
				$source_file = get_attached_file( $attachment_id );
				if(get_current_blog_id() == 7){
					echo "<!-- JIS ".__line__." SOURCE FILE: $source_file -->";
					$source_file = str_replace( '/sites/7/sites/3/', '/sites/3/', $source_file );
				}

                $image_editor = wp_get_image_editor( $source_file );
                if( ! is_wp_error( $image_editor ) ){
                    // maybe do face detection crop
                    if( $crop === 'face' ){
                        require_once(DIR_SCORECARD_SRC.'resizer/face-detector.php');
                        if( $this->detector === false ){
                            $this->detector = new FaceDetector();
                        }
                        $focal_point = $this->detector->faceDetect( get_attached_file( $attachment_id ) );
                        if( $focal_point ){
                            $crop = sanitize_focal_point( $focal_point );
                        }else{
                            $crop = sanitize_focal_point( get_post_meta( $attachment_id, 'focal_point', true ) );
                        }
                    }

                    // create new image
                    if( is_array( $crop ) && isset($crop[0]) && is_numeric( $crop[0] ) ){
                        // get original image size
                        $original_sizes = $image_editor->get_size();

                        // sanitize and distribute parameters
                        $dst_w = intval( $size[0] );
                        $dst_h = intval( $size[1] );
                        $focal_x = floatval( $crop[0] );
                        $focal_y = floatval( $crop[1] );

                        // maybe replace empty sizes
                        if( ! $dst_w ) $dst_w = $original_sizes['width'];
                        if( ! $dst_h ) $dst_h = $original_sizes['height'];

                        // calculate cropped image size
                        $src_w = $original_sizes['width'];
                        $src_h = $original_sizes['height'];

                        if( $original_sizes['width'] / $original_sizes['height'] > $dst_w / $dst_h ){
                            $src_w = round( $original_sizes['height'] * ( $dst_w / $dst_h ) );
                        }else{
                            $src_h = round( $original_sizes['width'] * ( $dst_h / $dst_w ) );
                        }

                        // calculate focal top left position
                        $src_x = $original_sizes['width'] * $focal_x - $src_w * $focal_x;
                        if( $src_x + $src_w > $original_sizes['width'] ){
                            $src_x += $original_sizes['width'] - $src_w - $src_x;
                        }
                        if( $src_x < 0 ){
                            $src_x = 0;
                        }
                        $src_x = round( $src_x );

                        $src_y = $original_sizes['height'] * $focal_y - $src_h * $focal_y;
                        if( $src_y + $src_h > $original_sizes['height'] ){
                            $src_y += $original_sizes['height'] - $src_h - $src_y;
                        }
                        if( $src_y < 0 ){
                            $src_y = 0;
                        }
                        $src_y = round( $src_y );
                        // crop and resize
                        $image_editor->crop( $src_x, $src_y, $src_w, $src_h, $dst_w, $dst_h );
                    }else{
                        $image_editor->resize( $width, $height, $crop );
                    }
                    $image_editor->save( $sis_file_path );

                    // Trigger action
                    do_action( 'sis_image_created', $attachment_id, $sis_file_path );

                    // Image created, return its data
                    $image_dimensions = $image_editor->get_size();
                    return array(
                        'src' => $this->get_sis_path( $sis_file_path ),
                        'width' => $image_dimensions['width'],
                        'height' => $image_dimensions['height'],
                    );
                }
            }
            // Something went wrong
            return array();
        }

        function get_attachment_image( $attachment_id = 0, $size = '', $crop = null, $attr = array() ){
            if( $attachment_id < 1 || empty( $size ) ){
                return '';
            }

            if( $size == 'full' || ! in_array( get_post_mime_type( $attachment_id ), SIS_ALLOWED_MIME_TYPES ) ){
                return wp_get_attachment_image( $attachment_id, $size, false, $attr );
            }

            $html = '';
            $image = $this->get_attachment_image_src( $attachment_id, $size, $crop );
            if( $image ){
                $hwstring = image_hwstring( $image['width'], $image['height'] );
                $size_class = $size;
                if( is_array( $size_class ) ){
                    $size_class = join( 'x', $size );
                }
                $attachment = get_post( $attachment_id );
                $default_attr = array(
                    'src' => $image['src'],
                    'class' => 'attachment-' . $size_class,
                    'alt' => trim( strip_tags( get_post_meta( $attachment_id, '_wp_attachment_image_alt', true ) ) ),
					//Templ add flag to indicate it's generated here
					'data-jis' => 'true',
                );
                if( empty( $default_attr['alt'] ) ){
                    $default_attr['alt'] = trim( strip_tags( $attachment->post_excerpt ) );
                }
                if( empty( $default_attr['alt'] ) ){
                    $default_attr['alt'] = trim( strip_tags( $attachment->post_title ) );
                }

                if( wp_lazy_loading_enabled( 'img', 'wp_get_attachment_image' ) ){
                    $default_attr['loading'] = 'lazy';
                }

                $attr = wp_parse_args( $attr, $default_attr );

                if( array_key_exists( 'loading', $attr ) && ! $attr['loading'] ){
                    unset( $attr['loading'] );
                }

                $attr = apply_filters( 'sis_get_attachment_image_attributes', $attr, $attachment, $size, $crop );

                $attr = array_map( 'esc_attr', $attr );
                $html = rtrim( "<img $hwstring" );
                foreach( $attr as $name => $value ){
                    $html .= " $name=" . '"' . $value . '"';
                }
                $html .= ' />';
            }

            return apply_filters( 'sis_get_attachment_image', $html, $attachment_id, $size, $attr );
        }

        function get_attachment_picture( $attachment_id = 0, $sizes = array(), $attr = array() ){
            if( $attachment_id < 1 || ! is_array( $sizes ) || count( $sizes ) === 0 ){
                return '';
            }
            ksort( $sizes );
            $last_breakpoint = 0;
            $html = '<picture>';
            foreach( $sizes as $breakpoint => $data ){
                if( intval( $breakpoint ) && count( $data ) >= 2 ){
                    $maybe_alternative_attachment_id = isset( $data[3] ) && $data[3] ? $data[3] : $attachment_id;
                    $img = sis_get_attachment_image_src( $maybe_alternative_attachment_id, array( $data[0], $data[1] ), isset( $data[2] ) ? $data[2] : false );
                    if( $img ){
                        if( isset( $attr['retina'] ) && $attr['retina'] ){
                            $retina = sis_get_attachment_image_src( $maybe_alternative_attachment_id, array( $data[0] * 2, $data[1] * 2 ), isset( $data[2] ) ? $data[2] : false );
                            $srcset = $img['src'] . ' 1x, ' . $retina['src'] . ' 2x';
                        }else{
                            $srcset = $img['src'];
                        }
                        $html .= '<source media="(max-width:' . intval( $breakpoint ) . 'px)" srcset="' . $srcset . '">';
                        $last_breakpoint = intval( $breakpoint );
                    }
                }
            }
            $html .= '<source media="(min-width:' . ( $last_breakpoint + 1 ) . 'px)" srcset="' . wp_get_attachment_url( $attachment_id ) . '">';
            $html .= wp_get_attachment_image( $attachment_id, 'full', false, $attr );
            $html .= '</picture>';
            return apply_filters( 'sis_get_attachment_picture', $html, $attachment_id, $sizes, $attr );
        }

        function retina_attribute( $attr, $attachment, $size, $crop ){
            if( isset( $attr['retina'] ) ){
                unset( $attr['retina'] );
                $imgx2 = sis_get_attachment_image_src( $attachment->ID, array( $size[0] * 2, $size[1] * 2 ), $crop );
                $attr['srcset'] = $attr['src'] . ' 1x, ' . $imgx2['src'] . ' 2x';
            }
            return $attr;
        }
    }

    new sis_image_sizes_resizer();
}

//Switch to sis_... functions to make them easier to find in the code
if( ! function_exists('sis_get_attachment_image_src') ){
    function sis_get_attachment_image_src( $attachment_id = 0, $size = '', $crop = null ){
        return (new sis_image_sizes_resizer)->get_attachment_image_src( $attachment_id, $size, $crop );
    }
}

if( ! function_exists('sis_get_attachment_image') ){
    function sis_get_attachment_image( $attachment_id = 0, $size = '', $crop = null, $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_image( $attachment_id, $size, $crop, $attr );
    }
}

if( ! function_exists('sis_get_attachment_picture') ){
    function sis_get_attachment_picture( $attachment_id = 0, $sizes = array(), $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_picture( $attachment_id, $sizes, $attr );
    }
}

//Fall back functions for previous versions of the plugin
/*
if( ! function_exists('fly_get_attachment_image') ){
    function fly_get_attachment_image( $attachment_id = 0, $size = '', $crop = null, $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_image( $attachment_id, $size, $crop, $attr );
    }
}

if( ! function_exists('bis_get_attachment_image') ){
    function bis_get_attachment_image( $attachment_id = 0, $size = '', $crop = null, $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_image( $attachment_id, $size, $crop, $attr );
    }
}

if( ! function_exists('bis_get_attachment_image_src') ){
    function bis_get_attachment_image_src( $attachment_id = 0, $size = '', $crop = null ){
        return (new sis_image_sizes_resizer)->get_attachment_image_src( $attachment_id, $size, $crop );
    }
}
*/
//JIS BACKWARD COMPATIBILITY
if( ! function_exists('jis_get_attachment_image_src') ){
    function jis_get_attachment_image_src( $attachment_id = 0, $size = '', $crop = null ){
        return (new sis_image_sizes_resizer)->get_attachment_image_src( $attachment_id, $size, $crop );
    }
}

if( ! function_exists('jis_get_attachment_image') ){
    function jis_get_attachment_image( $attachment_id = 0, $size = '', $crop = null, $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_image( $attachment_id, $size, $crop, $attr );
    }
}

if( ! function_exists('jis_get_attachment_picture') ){
    function jis_get_attachment_picture( $attachment_id = 0, $sizes = array(), $attr = array() ){
        return (new sis_image_sizes_resizer)->get_attachment_picture( $attachment_id, $sizes, $attr );
    }
}
